import { Navbar } from '@/components/Navbar';

export const metadata = {
  title: 'Terms of Service | SafeSponsor AI',
  description: 'Terms of service for SafeSponsor AI brand safety analysis platform.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-200">
      <Navbar />
      <main className="max-w-3xl mx-auto px-4 py-16 sm:py-24">
        <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
        <div className="space-y-6 text-zinc-400 text-sm leading-relaxed">
          <p><em>Last updated: August 4, 2026</em></p>

          <h2 className="text-lg font-semibold text-zinc-200 pt-4">1. Acceptance of Terms</h2>
          <p>
            By accessing or using SafeSponsor AI, you agree to be bound by these Terms of Service. 
            If you do not agree, do not use the platform.
          </p>

          <h2 className="text-lg font-semibold text-zinc-200 pt-4">2. Service Description</h2>
          <p>
            SafeSponsor AI provides AI-powered brand safety analysis for YouTube and Instagram creators. 
            Our tool analyzes publicly available data to generate risk assessments for sponsorship decisions. 
            Results are informational and do not constitute legal or financial advice.
          </p>

          <h2 className="text-lg font-semibold text-zinc-200 pt-4">3. Account Registration</h2>
          <p>
            You must create an account using Google Sign-In to access the platform. 
            You are responsible for maintaining the security of your account.
          </p>

          <h2 className="text-lg font-semibold text-zinc-200 pt-4">4. Payments</h2>
          <p>
            Paid plans are processed through Dodo Payments. All prices are in USD. 
            Subscriptions renew automatically unless cancelled before the billing period ends. 
            Single and channel report credits do not expire.
          </p>

          <h2 className="text-lg font-semibold text-zinc-200 pt-4">5. Refund Policy</h2>
          <p>
            Due to the digital nature of our services, refunds are handled on a case-by-case basis. 
            Contact us within 7 days of purchase if you experience issues with your order.
          </p>

          <h2 className="text-lg font-semibold text-zinc-200 pt-4">6. Acceptable Use</h2>
          <p>
            You agree not to abuse the platform, attempt unauthorized access, 
            use automated scripts to bypass rate limits, or use the service for any unlawful purpose.
          </p>

          <h2 className="text-lg font-semibold text-zinc-200 pt-4">7. Intellectual Property</h2>
          <p>
            Audit reports generated by SafeSponsor AI are yours to use. 
            The platform, its code, and design are the intellectual property of SafeSponsor AI.
          </p>

          <h2 className="text-lg font-semibold text-zinc-200 pt-4">8. Limitation of Liability</h2>
          <p>
            SafeSponsor AI is provided &quot;as is&quot; without warranties. We are not liable for any damages 
            arising from the use of our platform or reliance on audit results.
          </p>

          <h2 className="text-lg font-semibold text-zinc-200 pt-4">9. Termination</h2>
          <p>
            We reserve the right to terminate accounts that violate these terms. 
            You may delete your account at any time from the dashboard.
          </p>

          <h2 className="text-lg font-semibold text-zinc-200 pt-4">10. Contact</h2>
          <p>
            For questions about these terms, contact{' '}
            <a href="mailto:pandejesal@gmail.com" className="text-cyan-400 hover:underline">
              pandejesal@gmail.com
            </a>.
          </p>
        </div>
      </main>
    </div>
  );
}
